### ISSUE TITLE
Display exact number of raindrops for players

### ISSUE THREAD

**Issue by twizmwazin** [SunshineAPI/WebAPI#14]
Currently, it displays what Overcast prints directly on the website. In a browser, by hovering over the number it displays the exact number. This could allow for clients then to decide to retain the exact value or not.

**Comment by jacobbearden** [comment]
changed

**Comment by gilrosenthal** [comment]
@jacobbearden is it done?

**Comment by gilrosenthal** [comment]
it is done.
