### ISSUE TITLE
Response Caching

### ISSUE THREAD

**Issue by jengel3** [SunshineAPI/WebAPI#20]
Prevents us from hitting Overcast, instead caching responses for 30 seconds to several hours depending on the endpoint.

**Comment by gilrosenthal** [comment]
We should cache every rotation for a day and the punishments for about 3 minutes, and maybe every player every 30 seconds? This way all of the non-changing endpoints would not be to constantly parsed and recached every day, while the players could still have relatively updated stats without DDoSing OCN
