### ISSUE TITLE
Matches Parsing

### ISSUE THREAD

**Issue by jengel3** [SunshineAPI/WebAPI#22]
Missing for some reason, totally forgot about it, anyone want to do it?

**Comment by jacobbearden** [comment]
I can, should all the players for each team be parsed?

**Comment by gilrosenthal** [comment]
I can do this later hopefully

**Comment by jengel3** [comment]
Just the list of players @jacobbearden, not all their stats of course.

**Comment by jacobbearden** [comment]
I meant the list, lol

**Comment by jengel3** [comment]
:+1:

**Comment by gilrosenthal** [comment]
@Jake0oo0  :smile_cat:
