### ISSUE TITLE
Forum Status

### ISSUE THREAD

**Issue by jacobbearden** [SunshineAPI/WebAPI#24]
whether a player is online on the forums or not at /players/

**Comment by gilrosenthal** [comment]
Dont have time today, sorry

**Comment by jacobbearden** [comment]
oops wrong # in commit am smart

**Comment by gilrosenthal** [comment]
@jacobbearden dank memes

**Comment by Szboy** [comment]
Was this ever done?

**Comment by jacobbearden** [comment]
Dont think so, I'll do it after work

**Comment by jacobbearden** [comment]
closing because dead project and this is in my issues list
